services:
  mongodb:
    image: mongo:8
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      - MONGO_INITDB_DATABASE=books
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/books --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
