spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: books
  docker:
    compose:
      lifecycle-management: start_and_stop
      start:
        command: up
      stop:
        command: down
        timeout: 1m
